name: flutter_app
description: "Vampir Koylu Online Oyunu"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase (Online altyapı için)
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.2
  firebase_auth: ^5.4.1

  # State Management (Durum yönetimi)
  flutter_riverpod: ^2.6.1

  # Görsel ve UI Araçları
  google_fonts: ^6.2.1
  lottie: ^3.1.3
  flutter_animate: ^4.5.0
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Görselleri buraya tanıtıyoruz
  assets:
    - assets/images/
    - assets/animations/
    - assets/icon/